### ISSUE TITLE
[BUG] Yarn install fails on node 16.x

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-client#105]
**Describe the bug**
Yarn install fails on node 16.x after moving to new major version of marked.

**To Reproduce**
1. Use node 16.x
2. Run yarn install

**Expected behavior**
Either roll back version of marked or stop supporting node 16.x (and if so remove the github action job)

**Comment by havfo** [comment]
16 is EOL very soon, so let's remove it :+1:
