### ISSUE TITLE
[FEATURE REQUEST] Topbar icon color in config.js

### ISSUE THREAD

**Issue by olivierb2** [edumeet/edumeet-client#180]
Dear edumeet,

I'm currently caring of doing Debian package in same time of try to do proper deployment of Edumeet 4.

But I'm handling an issue with our logo and topbar. On login page, the logo will sits on a white background while top bar should remain dark, otherwise the icons will not be properly displayed.

I looked into code, but I found no way to change the icon color.

Do you think it could be a good idea to add a color setting in config.js?

Here an example if I put the topbar white.

![image](https://github.com/edumeet/edumeet-client/assets/2324018/f70e9bd1-b778-4c69-9e18-c3d02f203637)

**Comment by N7Remus** [comment]
Hi,

You can already do this if you change the theme options in the config.js:
```
 theme: {
        palette: {
            primary: {
                main: '#242943', // textbutton colors
            }
        },
        appBarColor: 'rgba(217, 217, 217, 0.4)', // TopBar background color
    },
};
```

**Comment by olivierb2** [comment]
Hi @N7Remus,

Many thanks for your reply, I din't realized primary also change textbutton colors.

Unfortunatelly, this cause a new issue (I put primary.main as '#FFF').

The tab text in settings become white as well (here APPEARANCE is now invisible).

![image](https://github.com/edumeet/edumeet-client/assets/2324018/f55935b1-d829-4e1d-b58e-3f881f4a7f40)

**Comment by olivierb2** [comment]
Okay, I got the idea. If we configure primary color with light color, icon become black. If Dark, icon become white. I don't realized there is this kind of calculation. So everything is all good !
