### ISSUE TITLE
Voice activated unmute

### ISSUE THREAD

**Issue by so010** [edumeet/edumeet-client#21]
re-implement feature of automatic unmute if audio activity above adjustable slider (for audio-level) is detected

**Comment by havfo** [comment]
Do we still want this?

**Comment by so010** [comment]
I would rather have a well implemented (client side) audio filtering when unmuted, which quantifies voice, technical noise, physical background noise (background voices, keyboard typing, coughing, ...) and then decides when there is high enough voice activity / noise ratio to actually transmit that audio to the room. And that filter should be as default active for all unmuted participants.
If that is not achievable - we want voice activated unmute (as non default)
This was well discussed with some users who pretended that they really needed that for gaming group chat like on Discourse.

**Comment by pnts-se** [comment]
It's very confusing with live code, commented-out code, configuration and documentation that is not wrong/not used. 

@so010 If it's ok, I'll clean up documentation, configuration and code to represent the current state of the service when it comes to noiseThreshold and auto-activated unmute. Then we could easily re-implement what we decide at a later stage.
