### ISSUE TITLE
[FEATURE REQUEST] Blur video background

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-client#52]
**Is your feature request related to a problem? Please describe.**
To blur video background is a common feature users expect of a video meeting service.
When using Edumeet you suddenly need to consider the environment around you.
It becomes a problem since baseline expectations involves blur video background feature.

**Describe the solution you'd like**
A blur video background checkbox in join dialog.
A setting for this in video settings when in a meeting.

**Describe alternatives you've considered**
There's no alternative.

**Implemetation**
- [x] blur video feature
    - [x] checkbox in join dialog
    - [x] in-meeting setting 
- ~~[ ] performance test suite~~

**Comment by havfo** [comment]
https://github.com/tensorflow/tfjs-models/tree/master/body-segmentation/demos

**Comment by pnts-se** [comment]
@havfo Interesting! I'll look into it and try to build something. For this, perhaps it could be relevant with a performance test suite. I could look into that as well.

**Comment by Alex-YddeR** [comment]
https://google.github.io/mediapipe/solutions/selfie_segmentation.html

**Comment by pnts-se** [comment]
I'll leave out performance test suite. Let's do it if and when we want to compare ML backend/model with something else, e.g. BodyPix.
