### ISSUE TITLE
edumeet-client using Legacy Root API

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-client#53]
**Describe the bug**
We're using ReactDOM.render to mount root.
It's no longer supported in React 18. 
Until you switch to the new API, edumet-client will behave as if it's running React 17. 

Perhaps nothing urgent, but we should consider migrating to the new API at some point.

Learn more: https://reactjs.org/link/switch-to-createroot
Migrating to new Root API: https://github.com/reactwg/react-18/discussions/5

**To Reproduce**
1. Load app in browser
2. Check console
3. find warning about ReactDOM.render

**Comment by havfo** [comment]
Yes, this is because we can't migrate to the newest version of react-scripts because that pulls in the latest version of webpack, which breaks webtorrent. Let's keep this issue to track progress on this :+1:
