### ISSUE TITLE
Wrong bandwidth displayed in stats view

### ISSUE THREAD

**Issue by havfo** [edumeet/edumeet-client#66]
The send/receive bandwidth shown in the stats view is wrong. Not exactly sure how it is wrong, but might be off by a factor of 10 or wrong conversion between bits/bytes.

![Peek 19-02-2023 14-56](https://user-images.githubusercontent.com/920922/219952835-e8edc169-a32c-4c72-9add-b77ace2d3717.gif)

![Peek 19-02-2023 14-55](https://user-images.githubusercontent.com/920922/219952779-1ec23c9a-cbe7-4046-bb9e-ca8fd6b28c22.gif)

**Comment by balazskreith** [comment]
Which browser you see it? Can you take a screenshot?

**Comment by balazskreith** [comment]
https://github.com/edumeet/edumeet-client/pull/74
