### ISSUE TITLE
[BUG] Audio settings is brocken

### ISSUE THREAD

**Issue by so010** [edumeet/edumeet-client#68]
Switching in advanced audio settings "Auto gain control" or "Noise supression" quite often switches mic to another source and applies not the correct settings. e.g. for me switching off Noise supression sets the selected audio input device to default, switching noise supression back to on again will not activate noise supression at all. In the UI all switches react but the don't get applied to the audio mostly. Audio is often changed but not in the expected way. The hole dialog works not as expected and feels broken. Somehow the same applies to all other advanced audio settings. 

 - Browser chrome Version 111.0.5563.64 (Official Build) (64-bit)

**Comment by pnts-se** [comment]
@so010 I can't reproduce this.  
It seems to work for me and I can verify every change in the console, e.g:  

 `document.getElementById('edumeet')._reactRootContainer.current.memoizedState.element.props.children[1].props.store.getState().settings.echoCancellation `

 `document.getElementById('edumeet')._reactRootContainer.current.memoizedState.element.props.children[1].props.store.getState().settings.selectedAudioDevice `

Can you explain how you verify the bug?
