### ISSUE TITLE
[BUG] Join button not disabled after clicked once

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-client#75]
**Describe the bug**
On lower bandwidth, you're able to click the join buttons multiple times.
Resulting in multiple toast messages, after successful join.

**To Reproduce**
1. Throttle bandwidth
2. Click join a lot of times
3. See multiple toast messages

**Expected behavior**
Disable join button while waiting on async functions.

**Screenshots**
![image](https://user-images.githubusercontent.com/66301426/227535307-df6e5787-8f79-47d1-a15b-b850dae13813.png)

**Comment by Dev-Mikko** [comment]
@pnts-se fixed
