### ISSUE TITLE
[BUG] Join button hidden on iOS

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-client#77]
**Describe the bug**
When I try to join a meeting on iOS (firefox, safari or chrome) a toast message hides the join button, which is very annoying.

**To Reproduce**
1. Try to join a meeting on iOS
2. Watch toast message hide join button.

**Expected behavior**
I'm expecting not having to wait for the toast message to disappear.

**Screenshots**
<img src="https://user-images.githubusercontent.com/66301426/228515174-81c5f8b7-ed55-4d36-995d-78431450c5d3.png" width="400px" />

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.3.1
 - Browser Safari
 - Version 16.3
 - Browser Firefox
 - Version 111.1
 - Browser Chrome 
 - Version 111.5563.101

**Comment by Dev-Mikko** [comment]
@pnts-se done. I think that I found a good solution to solve this problem

**Comment by Dev-Mikko** [comment]
Thank you @pnts-se 😄
