### ISSUE TITLE
[BUG] Can't access media controls on small viewport sizes

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-client#85]
**Describe the bug**
When using edumeet on small viewport sizes, your media controls are unreachable when more than 3 participants.
I think that should be fixed, and also think we perhaps should redesign the mobile experience.

A suggestion is to only show one remote participant on mobile, last active speaker?
Perhaps have the choice to move between different participants using left/right arrow icons?
Also, as we're on a small viewport, make remote participant fullscreen width and don't show background.

**To Reproduce**
1. Connect to a meeting using small viewport size. I was using iPhone 14 Pro (393 x 852)
2. Have more than 3 participants in the meeting.
3. You can't access media controls properly.

**Expected behavior**
I expect to easily be able to access media controls.
I also expect to have a mobile friendly experience, IMO a single remote participant using last active speaker mode is acceptable.

**Screenshots**
<img src="https://user-images.githubusercontent.com/66301426/233942604-d965b4d3-ab25-43e1-8819-f7d6c2e63304.jpeg" width="400px">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.3.1
 - Browser safari
 - Version 16

**Additional context**
If others agree on updating the mobile experience perhaps we should have a meeting discussing it.

**Comment by Dev-Mikko** [comment]
It is a well-known problem. We must find a way to improve the UI in situations like that. A brief discussion was done some weeks ago but, for the moment, no solution has been provided.
