### ISSUE TITLE
[BUG] Privacy-preserving screen sharing controls

### ISSUE THREAD

**Issue by N7Remus** [edumeet/edumeet-client#94]
https://developer.chrome.com/docs/web-platform/screen-sharing-controls/

update recorder

**Comment by N7Remus** [comment]
Also screenshare

**Comment by Dev-Mikko** [comment]
@N7Remus since I am working on features related to screensharing, I fixed the problem and pushed the solution

**Comment by Dev-Mikko** [comment]
@N7Remus I see now that you make the changes in this branch: https://github.com/edumeet/edumeet-client/tree/screen . I remove my PR now.

**Comment by N7Remus** [comment]
Merged
